#     
#        _____ __                            _                _____                          
#       / ___// /_________  ____ _____ ___  (_)___  ____ _   / ___/___  ______   _____  _____
#       \__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ / __ \/ __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
#      ___/ / /_/ /  /  __/ /_/ / / / / / / / / / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
#     /____/\__/_/   \___/\__,_/_/ /_/ /_/_/_/ /_/\__, /   /____/\___/_/    |___/\___/_/     
#                                                /____/                                      
#   Need  "ronix-net" Network for Run this File
#   docker network create --driver bridge --subnet=150.50.50.0/24 ronix-net


version: "3.3"
services:
  kaltura:
    container_name: 'kaltura'
    image: dockerhub.ronix.ir/nginx-vod-module:latest
    hostname: kaltura
    ports:
      - 8800:80
      - 8443:443
    volumes:
      - /videoFiles/videos:/opt/static/videos
      - ./config/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - ronix-net
    restart: always

networks:
  ronix-net:
    external: true


