#     
#        _____ __                            _                _____                          
#       / ___// /_________  ____ _____ ___  (_)___  ____ _   / ___/___  ______   _____  _____
#       \__ \/ __/ ___/ _ \/ __ `/ __ `__ \/ / __ \/ __ `/   \__ \/ _ \/ ___/ | / / _ \/ ___/
#      ___/ / /_/ /  /  __/ /_/ / / / / / / / / / / /_/ /   ___/ /  __/ /   | |/ /  __/ /    
#     /____/\__/_/   \___/\__,_/_/ /_/ /_/_/_/ /_/\__, /   /____/\___/_/    |___/\___/_/     
#                                                /____/                                      
#   Need  "my-net" Network for Run this File
#   docker network create --driver bridge --subnet=150.50.50.0/24 my-net
version: "3.3"
services:
  kaltura:
    container_name: 'kaltura'
    image: ghcr.io/beigi-reza/nginx-vod-module:latest
    hostname: kaltura
    ports:
      - 80:80
      - 443:443
    volumes:
      - /videoFiles/videos:/opt/static/videos
      - ./config/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - my-net
    restart: always

networks:
  my-net:
    external: true


